cppexpose: cppexpose::ComponentManager Class Reference
cppexpose::ComponentManager Class Reference
Class for managing components and plugins.
#include <cppexpose/include/cppexpose/plugin/ComponentManager.h>
Public Member Functions
ComponentManager ()
Constructor.
ComponentManager (const ComponentManager &)=delete
Copy constructor (deleted)
virtual ~ComponentManager ()
Destructor.
ComponentManager & operator= (const ComponentManager &)=delete
Copy assignment operator (deleted)
const std::vector< std::string > & pluginPaths (PluginPathType type=PluginPathType::UserDefined) const
Get plugin paths.
void addPluginPath (const std::string &path, PluginPathType type=PluginPathType::UserDefined)
Add plugin path.
void removePluginPath (const std::string &path)
Remove plugin path.
void scanPlugins (const std::string &suffix="", bool reload=false)
Scan for plugins and load all found ones.
bool loadPlugin (const std::string &filePath, bool reload=true)
Load plugin library.
std::vector< PluginLibrary * > pluginLibraries () const
Get list of loaded plugin libraries.
const std::vector< AbstractComponent * > & components () const
Get list of available components.
template<typename BaseType >
std::vector< typename ComponentTypes< BaseType >::AbstractComponentType * > components () const
Get list of available components of a specific type.
AbstractComponent * component (const std::string &name) const
Get component by name.
template<typename BaseType >
ComponentTypes< BaseType >::AbstractComponentType * component (const std::string &name) const
Get typed component.
void printComponents () const
Print list of available components to log.
Static Public Member Functions
static ComponentRegistry & registry ()
Get component registry.
Public Attributes
Signal componentsChanged
Called when a component has been added.
Protected Member Functions
bool loadLibrary (const std::string &filePath, bool reload)
Load plugin library and add all contained plugins.
void unloadLibrary (PluginLibrary *library)
Unload plugin library.
void addComponent (AbstractComponent *component)
Add component.
void updateComponents (PluginLibrary *library=nullptr) const
Update components.
Protected Attributes
std::vector< std::string > m_paths
Plugin paths (all)
std::vector< std::string > m_pathsInternal
Plugin paths (internal)
std::vector< std::string > m_pathsUser
Plugin paths (user defined)
std::vector< AbstractComponent * > m_components
Available components, statically initialized once per component class via the COMPONENT macro.
std::map< std::string, AbstractComponent * > m_componentsByName
Available components by name.
std::map< std::string, std::unique_ptr< PluginLibrary > > m_librariesByFilePath
Plugin libraries by path.
Detailed Description
Class for managing components and plugins.
This class manages a list of components, which can be instantiated dynamically. A component, which is in fact a factory object, can either be defined directly inside a library or application, or be loaded from a plugin library.
The component manager offers functionality to register components, list components (either all or per type), and get components by name. It also provides functions for search and loading plugin libraries, which in turn register components on the component manager.
Constructor & Destructor Documentation
cppexpose::ComponentManager::ComponentManager ()
Constructor.
cppexpose::ComponentManager::ComponentManager (const ComponentManager &) delete
Copy constructor (deleted)
virtual cppexpose::ComponentManager::~ComponentManager () virtual
Destructor.
Member Function Documentation
static ComponentRegistry& cppexpose::ComponentManager::registry () static
Get component registry.
Returns
Component registry
ComponentManager& cppexpose::ComponentManager::operator= (const ComponentManager &) delete
Copy assignment operator (deleted)
const std::vector<std::string>& cppexpose::ComponentManager::pluginPaths (PluginPathType type = PluginPathType::UserDefined) const
Get plugin paths.
Parameters
[in] type Plugin path type
Returns
List of paths that are searched for plugins
void cppexpose::ComponentManager::addPluginPath (const std::string & path, PluginPathType type = PluginPathType::UserDefined)
Add plugin path.
Parameters
[in] path Plugin path
[in] type Plugin path type
Remarks
If path is empty or already in the path list, the path list is not changed. If no plugin path is provided, the default application path is used. The type must be either UserDefined or Internal, calls to addPluginPath with PluginPathType::All are ignored.
void cppexpose::ComponentManager::removePluginPath (const std::string & path)
Remove plugin path.
Parameters
[in] path Plugin path
void cppexpose::ComponentManager::scanPlugins (const std::string & suffix = "", bool reload = false)
Scan for plugins and load all found ones.
Parameters
[in] suffix Load only libraries with the given suffix. If empty, all libraries are loaded.
[in] reload Reload plugin libraries that are already loaded?
bool cppexpose::ComponentManager::loadPlugin (const std::string & filePath, bool reload = true)
Load plugin library.
Parameters
[in] filePath Path to the plugin library
[in] reload Reload plugin libraries that are already loaded?
Returns
'true' if library has been loaded successfully, else 'false'
std::vector<PluginLibrary *> cppexpose::ComponentManager::pluginLibraries () const
Get list of loaded plugin libraries.
Returns
List of plugin libraries
const std::vector<AbstractComponent *>& cppexpose::ComponentManager::components () const
Get list of available components.
Returns
List of components
template<typename BaseType > std::vector< typename ComponentTypes< BaseType >::AbstractComponentType * > cppexpose::ComponentManager::components () const
Get list of available components of a specific type.
Returns
List of typed components
References component(), m_components, and updateComponents().
AbstractComponent* cppexpose::ComponentManager::component (const std::string & name) const
Get component by name.
Parameters
[in] name Component name
Returns
Pointer to the component, nullptr if no component with that name exists
Referenced by component(), and components().
template<typename BaseType > ComponentTypes< BaseType >::AbstractComponentType * cppexpose::ComponentManager::component (const std::string & name) const
Get typed component.
Parameters
[in] name Component name
Returns
Pointer to the component, nullptr if component doesn't exist or has the wrong type
References component().
void cppexpose::ComponentManager::printComponents () const
Print list of available components to log.
bool cppexpose::ComponentManager::loadLibrary (const std::string & filePath, bool reload) protected
Load plugin library and add all contained plugins.
Parameters
[in] filePath Path to library
[in] reload Reload plugin libraries that are already loaded?
Returns
'true' if library has been loaded successfully, else 'false'
void cppexpose::ComponentManager::unloadLibrary (PluginLibrary * library) protected
Unload plugin library.
Parameters
[in] library Plugin library
Remarks
Before calling the function, it must be made sure that the plugin library is not used anymore, i.e., no instances of the contained plugins must be remaining.
void cppexpose::ComponentManager::addComponent (AbstractComponent * component) protected
Add component.
Parameters
[in] component Component
void cppexpose::ComponentManager::updateComponents (PluginLibrary * library = nullptr) const protected
Update components.
Parameters
[in] library Plugin library (can be null)
Remarks
This function updates the component list by looking at the list of newly registered components and adding them to the component manager. If a library pointer is given, the found components are considered to belong to that library.
Referenced by components().
Member Data Documentation
Signal cppexpose::ComponentManager::componentsChanged
Called when a component has been added.
std::vector<std::string> cppexpose::ComponentManager::m_paths protected
Plugin paths (all)
std::vector<std::string> cppexpose::ComponentManager::m_pathsInternal protected
Plugin paths (internal)
std::vector<std::string> cppexpose::ComponentManager::m_pathsUser protected
Plugin paths (user defined)
std::vector<AbstractComponent *> cppexpose::ComponentManager::m_components protected
Available components, statically initialized once per component class via the COMPONENT macro.
Referenced by components().
std::map<std::string, AbstractComponent *> cppexpose::ComponentManager::m_componentsByName protected
Available components by name.
std::map<std::string, std::unique_ptr<PluginLibrary> > cppexpose::ComponentManager::m_librariesByFilePath protected
Plugin libraries by path.
The documentation for this class was generated from the following files:
ComponentManager.h
ComponentManager.inl