cppexpose: cppexpose::AbstractProperty Class Reference
cppexpose::AbstractProperty Class Reference abstract
Base class for properties.
#include <cppexpose/include/cppexpose/reflection/AbstractProperty.h>
Public Member Functions
AbstractProperty ()
Constructor.
AbstractProperty (const Variant &options)
Constructor.
virtual ~AbstractProperty ()
Destructor.
const std::string & name () const
Get name.
void setName (const std::string &name)
Set name.
std::string qualifiedName (const Object *relativeRoot=nullptr) const
Get qualified name.
Object * parent () const
Get parent object.
bool hasParent () const
Finds out whether the Object has a parent.
virtual bool isObject () const =0
Check if property is an object.
const VariantMap & options () const
Get options of property.
void setOptions (const VariantMap &map)
Set options of property.
bool hasOption (const std::string &key) const
Check if option is set.
const Variant & option (const std::string &key) const
Get option of property.
template<typename Type >
Type option (const std::string &key, const Type &defaultValue=Type()) const
Get option of property convert to a specific type.
void setOption (const std::string &key, const Variant &value)
Set option of property.
bool removeOption (const std::string &key)
Remove option of property.
Public Attributes
Signal< AbstractProperty * > beforeDestroy
Called before a property is destroyed.
Signal< const std::string & > optionChanged
Called when an option of the property has been changed.
Protected Member Functions
void initProperty (const std::string &name, Object *parent)
Initialize property.
void setParent (Object *parent)
Set parent object.
virtual void onOptionChanged (const std::string &option)
Called when an option of the property has changed.
Protected Attributes
std::string m_name
Name of the property.
Object * m_parent
Parent object.
VariantMap m_options
Additional options for the property (e.g., minimum or maximum values)
Friends
class Object
Detailed Description
Base class for properties.
Constructor & Destructor Documentation
cppexpose::AbstractProperty::AbstractProperty ()
Constructor.
cppexpose::AbstractProperty::AbstractProperty (const Variant & options)
Constructor.
Parameters
[in] options Options with which the property is initialized
virtual cppexpose::AbstractProperty::~AbstractProperty () virtual
Destructor.
Member Function Documentation
const std::string& cppexpose::AbstractProperty::name () const
Get name.
Returns
Name
Referenced by cppexpose::Object::addProperty(), and cppexpose::Object::createDynamicProperty().
void cppexpose::AbstractProperty::setName (const std::string & name)
Set name.
Parameters
[in] name Name
Remarks
This function should never be called after the property has been added to a parent object. The name change will not be updated in the parent container.
std::string cppexpose::AbstractProperty::qualifiedName (const Object * relativeRoot = nullptr) const
Get qualified name.
Parameters
[in] relativeRoot (optional) Root object for relative name resolution
Returns
Qualified name
Remarks
Returns ablosute qualified name if relativeRoot is not found in ancestral hierarchy
Object* cppexpose::AbstractProperty::parent () const
Get parent object.
Returns
Parent (can be null)
bool cppexpose::AbstractProperty::hasParent () const
Finds out whether the Object has a parent.
Returns
false if the parent is null, otherwise true
virtual bool cppexpose::AbstractProperty::isObject () const pure virtual
Check if property is an object.
Returns
'true' if property is an object, else 'false'
Implemented in cppexpose::Object.
const VariantMap& cppexpose::AbstractProperty::options () const
Get options of property.
Options provide additional meta information about a property. Use options to add, e.g., minimum and maximum values, affixes, or flags. These can be used to configure editor widgets. Look at the class documentation of the specific property type to get a list of supported options.
Returns
List of options
void cppexpose::AbstractProperty::setOptions (const VariantMap & map)
Set options of property.
Parameters
[in] map List of options
bool cppexpose::AbstractProperty::hasOption (const std::string & key) const
Check if option is set.
Parameters
[in] key Option name
Returns
'true' if the option is set, else 'false'
const Variant& cppexpose::AbstractProperty::option (const std::string & key) const
Get option of property.
Parameters
[in] key Option name
Returns
Option value
Referenced by option().
template<typename Type > Type cppexpose::AbstractProperty::option (const std::string & key, const Type & defaultValue = Type()) const
Get option of property convert to a specific type.
Parameters
[in] key Option name
[in] defaultValue Default value
Returns
Option value converted to Type, defaultValue if the option doesn't exist or couldn't be converted
References option().
void cppexpose::AbstractProperty::setOption (const std::string & key, const Variant & value)
Set option of property.
Parameters
[in] key Option name
[in] value Option value
bool cppexpose::AbstractProperty::removeOption (const std::string & key)
Remove option of property.
Parameters
[in] key Option name
Returns
'true' if the option has been removed, else 'false'
void cppexpose::AbstractProperty::initProperty (const std::string & name, Object * parent) protected
Initialize property.
Parameters
[in] name Name (can be empty)
[in] parent Parent object (can be null)
[in] ownership Property ownership
Remarks
The internal parent is updated to the parent parameter. Do not set m_parent before calling this function, otherwise the property might be rejected when added to the parent.
void cppexpose::AbstractProperty::setParent (Object * parent) protected
Set parent object.
Parameters
[in] parent Parent object (can be null)
Remarks
This function should only be called by Object when adding or removing properties.
virtual void cppexpose::AbstractProperty::onOptionChanged (const std::string & option) protected virtual
Called when an option of the property has changed.
Parameters
[in] option Name of the option
Remarks
This function is empty be default and can be implemented in derived classes.
Friends And Related Function Documentation
friend class Object friend
Member Data Documentation
Signal<AbstractProperty *> cppexpose::AbstractProperty::beforeDestroy
Called before a property is destroyed.
Signal<const std::string &> cppexpose::AbstractProperty::optionChanged
Called when an option of the property has been changed.
std::string cppexpose::AbstractProperty::m_name protected
Name of the property.
Object* cppexpose::AbstractProperty::m_parent protected
Parent object.
VariantMap cppexpose::AbstractProperty::m_options protected
Additional options for the property (e.g., minimum or maximum values)
The documentation for this class was generated from the following files:
AbstractProperty.h
AbstractProperty.inl