cppexpose: cppexpose::ConstMemberFunction< T, RET, Arguments > Class Template Reference
cppexpose::ConstMemberFunction< T, RET, Arguments > Class Template Reference
Representation of a const member function.
#include <cppexpose/include/cppexpose/function/ConstMemberFunction.h>
Public Types
typedef RET(T::* Func) (Arguments...) const
Typed function pointer for a member function of class T.
Public Member Functions
ConstMemberFunction (const T *obj, Func func)
Constructor.
virtual ~ConstMemberFunction ()
Destructor.
virtual std::unique_ptr< AbstractFunction > clone () override
Create a copy of the function object.
virtual Variant call (const std::vector< Variant > &args) override
Call function.
Public Member Functions inherited from cppexpose::AbstractFunction
AbstractFunction ()
Constructor.
virtual ~AbstractFunction ()
Destructor.
Protected Member Functions
template<size_t... I>
Variant callMethod (helper::Seq< I... >, const std::vector< Variant > &args)
Protected Attributes
const T * m_obj
Pointer to instance of class T.
Func m_func
Function object (for non-const function)
Detailed Description
template<class T, typename RET, typename... Arguments>
class cppexpose::ConstMemberFunction< T, RET, Arguments >
Representation of a const member function.
Member Typedef Documentation
template<class T , typename RET , typename... Arguments> typedef RET(T::* cppexpose::ConstMemberFunction< T, RET, Arguments >::Func) (Arguments...) const
Typed function pointer for a member function of class T.
Constructor & Destructor Documentation
template<class T , typename RET , typename... Arguments> cppexpose::ConstMemberFunction< T, RET, Arguments >::ConstMemberFunction (const T * obj, Func func)
Constructor.
Parameters
[in] obj Pointer to object
[in] func Pointer to member function
template<class T , typename RET , typename... Arguments> cppexpose::ConstMemberFunction< T, RET, Arguments >::~ConstMemberFunction () virtual
Destructor.
Member Function Documentation
template<class T , typename RET , typename... Arguments> std::unique_ptr< AbstractFunction > cppexpose::ConstMemberFunction< T, RET, Arguments >::clone () override virtual
Create a copy of the function object.
Returns
New function object pointing to the same function. Has to be deleted by the caller.
Implements cppexpose::AbstractFunction.
References cppexpose::ConstMemberFunction< T, RET, Arguments >::m_func, and cppexpose::ConstMemberFunction< T, RET, Arguments >::m_obj.
template<class T , typename RET , typename... Arguments> Variant cppexpose::ConstMemberFunction< T, RET, Arguments >::call (const std::vector< Variant > & args) override virtual
Call function.
Parameters
[in] args List of arguments as Variants
Returns
New function object pointing to the same function. Has to be deleted by the caller.
Implements cppexpose::AbstractFunction.
References cppexpose::ConstMemberFunction< T, RET, Arguments >::callMethod().
template<class T , typename RET , typename... Arguments> template<size_t... I> Variant cppexpose::ConstMemberFunction< T, RET, Arguments >::callMethod (helper::Seq< I... > , const std::vector< Variant > & args) protected
References cppexpose::helper::CallConstMethod< T, RET, Arguments >::call(), cppexpose::ConstMemberFunction< T, RET, Arguments >::m_func, and cppexpose::ConstMemberFunction< T, RET, Arguments >::m_obj.
Referenced by cppexpose::ConstMemberFunction< T, RET, Arguments >::call().
Member Data Documentation
template<class T , typename RET , typename... Arguments> const T* cppexpose::ConstMemberFunction< T, RET, Arguments >::m_obj protected
Pointer to instance of class T.
Referenced by cppexpose::ConstMemberFunction< T, RET, Arguments >::callMethod(), and cppexpose::ConstMemberFunction< T, RET, Arguments >::clone().
template<class T , typename RET , typename... Arguments> Func cppexpose::ConstMemberFunction< T, RET, Arguments >::m_func protected
Function object (for non-const function)
Referenced by cppexpose::ConstMemberFunction< T, RET, Arguments >::callMethod(), and cppexpose::ConstMemberFunction< T, RET, Arguments >::clone().
The documentation for this class was generated from the following files:
ConstMemberFunction.h
ConstMemberFunction.inl