cppexpose: cppexpose::Signal< Arguments > Class Template Reference
cppexpose::Signal< Arguments > Class Template Reference
Signal class for communicating events.
#include <cppexpose/include/cppexpose/signal/Signal.h>
Public Types
using Callback = std::function< void(Arguments...)>
Signature for callbacks.
Public Member Functions
Signal ()
Constructor.
void operator() (Arguments...arguments)
Emit signal.
Connection connect (Callback callback) const
Connect signal to callback function.
template<class T , class U >
Connection connect (T *object, void(U::*method)(Arguments...)) const
Connect signal to member function of an object.
Connection connect (Signal &signal) const
Connect signal to another signal.
Connection onFire (std::function< void()> callback) const
Connect to when the signal is emitted.
void block ()
Block signal.
void unblock ()
Unblock signal.
Public Member Functions inherited from cppexpose::AbstractSignal
AbstractSignal ()
Constructor.
virtual ~AbstractSignal ()
Destructor.
Protected Member Functions
void fire (Arguments...arguments) const
Emit signal.
virtual void disconnectId (Connection::Id id) const override
Disconnect connection by ID.
Protected Member Functions inherited from cppexpose::AbstractSignal
Connection createConnection () const
Create new empty connection.
void disconnect (Connection &connection) const
Disconnect connection.
Protected Attributes
std::unordered_map< Connection::Id, Callback > m_callbacks
List of registered callbacks.
bool m_blocked
If 'true', the signal does not emit when invoked.
Protected Attributes inherited from cppexpose::AbstractSignal
Connection::Id m_nextId
Next free connection ID.
std::unordered_map< Connection::Id, Connection > m_connections
Map of connections by ID.
Detailed Description
template<typename... Arguments>
class cppexpose::Signal< Arguments >
Signal class for communicating events.
Member Typedef Documentation
template<typename... Arguments> using cppexpose::Signal< Arguments >::Callback = std::function<void(Arguments...)>
Signature for callbacks.
Constructor & Destructor Documentation
template<typename... Arguments> cppexpose::Signal< Arguments >::Signal ()
Constructor.
Member Function Documentation
template<typename... Arguments> void cppexpose::Signal< Arguments >::operator() (Arguments... arguments)
Emit signal.
Parameters
[in] arguments Signal arguments
References cppexpose::Signal< Arguments >::fire().
template<typename... Arguments> Connection cppexpose::Signal< Arguments >::connect (Callback callback) const
Connect signal to callback function.
Parameters
[in] callback Callback function that is invoked
References cppexpose::AbstractSignal::createConnection(), cppexpose::Connection::id(), and cppexpose::Signal< Arguments >::m_callbacks.
Referenced by cppexpose::Signal< Arguments >::connect(), and cppexpose::Signal< Arguments >::onFire().
template<typename... Arguments> template<class T , class U > Connection cppexpose::Signal< Arguments >::connect (T * object, void(U::*)(Arguments...) method) const
Connect signal to member function of an object.
Parameters
[in] object Object
[in] method Member function that is invoked
References cppexpose::Signal< Arguments >::connect().
template<typename... Arguments> Connection cppexpose::Signal< Arguments >::connect (Signal< Arguments > & signal) const
Connect signal to another signal.
Parameters
[in] signal Signal that is invoked
References cppexpose::Signal< Arguments >::connect().
template<typename... Arguments> Connection cppexpose::Signal< Arguments >::onFire (std::function< void()> callback) const
Connect to when the signal is emitted.
Parameters
[in] callback Callback function that is invoked
Remarks
This function can be used to connect a callback function to when the signal is emitted. It will be invoked just as a normal callback function, but does not contain the data of the signal.
References cppexpose::Signal< Arguments >::connect().
template<typename... Arguments> void cppexpose::Signal< Arguments >::block ()
Block signal.
Remarks
As long as the signal is blocked, it does not emit even if invoked
References cppexpose::Signal< Arguments >::m_blocked.
template<typename... Arguments> void cppexpose::Signal< Arguments >::unblock ()
Unblock signal.
References cppexpose::Signal< Arguments >::m_blocked.
template<typename... Arguments> void cppexpose::Signal< Arguments >::fire (Arguments... arguments) const protected
Emit signal.
Parameters
[in] arguments Signal arguments
References cppexpose::Signal< Arguments >::m_blocked, and cppexpose::Signal< Arguments >::m_callbacks.
Referenced by cppexpose::Signal< Arguments >::operator()().
template<typename... Arguments> void cppexpose::Signal< Arguments >::disconnectId (Connection::Id id) const override protected virtual
Disconnect connection by ID.
Parameters
[in] id Connection ID
Implements cppexpose::AbstractSignal.
References cppexpose::Signal< Arguments >::m_callbacks.
Member Data Documentation
template<typename... Arguments> std::unordered_map<Connection::Id, Callback> cppexpose::Signal< Arguments >::m_callbacks mutable protected
List of registered callbacks.
Referenced by cppexpose::Signal< Arguments >::connect(), cppexpose::Signal< Arguments >::disconnectId(), and cppexpose::Signal< Arguments >::fire().
template<typename... Arguments> bool cppexpose::Signal< Arguments >::m_blocked protected
If 'true', the signal does not emit when invoked.
Referenced by cppexpose::Signal< Arguments >::block(), cppexpose::Signal< Arguments >::fire(), and cppexpose::Signal< Arguments >::unblock().
The documentation for this class was generated from the following files:
Signal.h
Signal.inl