cppexpose: cppexpose::StaticFunction< RET, Arguments > Class Template Reference
cppexpose::StaticFunction< RET, Arguments > Class Template Reference
Representation of a static function.
#include <cppexpose/include/cppexpose/function/StaticFunction.h>
Public Types
typedef RET(* Func) (Arguments...)
Typed function pointer for a static function.
Public Member Functions
StaticFunction (Func func)
Constructor.
virtual ~StaticFunction ()
Destructor.
virtual std::unique_ptr< AbstractFunction > clone () override
Create a copy of the function object.
virtual Variant call (const std::vector< Variant > &args) override
Call function.
Public Member Functions inherited from cppexpose::AbstractFunction
AbstractFunction ()
Constructor.
virtual ~AbstractFunction ()
Destructor.
Protected Member Functions
template<size_t... I>
Variant callFunction (helper::Seq< I... >, const std::vector< Variant > &args)
Protected Attributes
Func m_func
Function object.
Detailed Description
template<typename RET, typename... Arguments>
class cppexpose::StaticFunction< RET, Arguments >
Representation of a static function.
Member Typedef Documentation
template<typename RET , typename... Arguments> typedef RET(* cppexpose::StaticFunction< RET, Arguments >::Func) (Arguments...)
Typed function pointer for a static function.
Constructor & Destructor Documentation
template<typename RET , typename... Arguments> cppexpose::StaticFunction< RET, Arguments >::StaticFunction (Func func)
Constructor.
Parameters
[in] func Pointer to static function
template<typename RET , typename... Arguments> cppexpose::StaticFunction< RET, Arguments >::~StaticFunction () virtual
Destructor.
Member Function Documentation
template<typename RET , typename... Arguments> std::unique_ptr< AbstractFunction > cppexpose::StaticFunction< RET, Arguments >::clone () override virtual
Create a copy of the function object.
Returns
New function object pointing to the same function. Has to be deleted by the caller.
Implements cppexpose::AbstractFunction.
References cppexpose::StaticFunction< RET, Arguments >::m_func.
template<typename RET , typename... Arguments> Variant cppexpose::StaticFunction< RET, Arguments >::call (const std::vector< Variant > & args) override virtual
Call function.
Parameters
[in] args List of arguments as Variants
Returns
New function object pointing to the same function. Has to be deleted by the caller.
Implements cppexpose::AbstractFunction.
References cppexpose::StaticFunction< RET, Arguments >::callFunction().
template<typename RET , typename... Arguments> template<size_t... I> Variant cppexpose::StaticFunction< RET, Arguments >::callFunction (helper::Seq< I... > , const std::vector< Variant > & args) protected
References cppexpose::helper::CallFunction< RET, Arguments >::call(), and cppexpose::StaticFunction< RET, Arguments >::m_func.
Referenced by cppexpose::StaticFunction< RET, Arguments >::call().
Member Data Documentation
template<typename RET , typename... Arguments> Func cppexpose::StaticFunction< RET, Arguments >::m_func protected
Function object.
Referenced by cppexpose::StaticFunction< RET, Arguments >::callFunction(), and cppexpose::StaticFunction< RET, Arguments >::clone().
The documentation for this class was generated from the following files:
StaticFunction.h
StaticFunction.inl